### ISSUE TITLE
Django Diary date picker bug

### ISSUE THREAD

**Issue by hendricksonsarahl** [codeforgoodconf/free-geek#93]
Add a new customer function of diary test app located at
http://127.0.0.1:8000/diary/customer_add/
date picker functions correctly as user is selecting year/month/day, but resulting date is not valid. Cannot be manually edited by user

**Comment by nickoneill** [comment]
I'll give this one a shot

**Comment by nickoneill** [comment]
The date picker sets the field in the format `DD/MM/YYYY`, but something is expecting `MM/DD/YYYY`. This means validating succeeds when you select a date with a day <= 12! Problem solved, as long as you weren't born in the later 2/3rds of any month!

Since this page is from django-diary, I checked that out by itself to see what the behavior was. Surprisingly it seems like it's fine? I'm looking around in both projects to find where freegeek was specifying a different date format but searching is turning up nothing and I'm not familiar enough with django to know precisely where to look. It looks like the date format ends up the same in the raw sqlite database so if it's generated in the same format and stored in the same format... where does it fail in between?

Still looking...

**Comment by hendricksonsarahl** [comment]
Thanks for the update Nick!

**Comment by mbrochmann** [comment]
this might be useful (search for "date_format", etc...) 

https://docs.djangoproject.com/en/1.11/ref/settings/

my guess is something needs to be changed in settings.py.

it might also be useful to look at the beginning of models.py, where some functions from the auth/admin models are using the DateTimeField object.

**Comment by nickoneill** [comment]
"Fixed" in #95
